[build]
  # Folder containing frontend (HTML/CSS/JS)
  publish = "public"
  # Folder containing Netlify Functions
  functions = "functions"

# Redirect all routes to index.html (SPA support)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
